"""Launcher and control pages. The coordinating window connects their actions."""
from PySide6.QtCore import Qt
from PySide6.QtWidgets import QBoxLayout, QCheckBox, QFormLayout, QLineEdit, QPlainTextEdit, QSpinBox, QStyle, QVBoxLayout, QWidget

from .components import Page, RemotePad, app_logo, button, label, row


class HomePage(Page):
    def __init__(self) -> None:
        super().__init__("Google TV", "Salem Google TV Emulator")
        self.state = label("Checking engine...", "status")
        self.serial = label("No active device", "muted")
        self.body.addLayout(row(app_logo(72), self.state))
        self.body.addWidget(self.serial)
        self.launch = button("Launch Google TV", "primary", QStyle.StandardPixmap.SP_MediaPlay)
        self.stop = button("Stop", "danger", QStyle.StandardPixmap.SP_MediaStop)
        self.restart = button("Restart", icon=QStyle.StandardPixmap.SP_BrowserReload)
        self.body.addLayout(row(self.launch, self.restart, self.stop))
        display = self.section("Display")
        self.tv_status = label("TV Mode off", "muted")
        self.enter_tv = button("Enter TV Mode", icon=QStyle.StandardPixmap.SP_TitleBarMaxButton)
        self.exit_tv = button("Exit TV Mode", icon=QStyle.StandardPixmap.SP_TitleBarNormalButton)
        display.addWidget(self.tv_status)
        display.addLayout(row(self.enter_tv, self.exit_tv))
        quick = self.section("Controls")
        self.remote = button("Remote", icon=QStyle.StandardPixmap.SP_ComputerIcon)
        self.popout = button("Pop-out Remote", icon=QStyle.StandardPixmap.SP_TitleBarNormalButton)
        quick.addLayout(row(self.remote, self.popout))
        engine = self.section("Engine")
        self.engine_status = label("Checking installed tools...", "muted")
        self.repair = button("Fix Everything & Launch", icon=QStyle.StandardPixmap.SP_BrowserReload)
        self.install = button("Install APK", icon=QStyle.StandardPixmap.SP_DialogOpenButton)
        engine.addWidget(self.engine_status)
        engine.addLayout(row(self.repair, self.install))
        self.activity = label("Ready when you are.", "muted")
        self.body.addStretch()
        self.body.addWidget(self.activity)


class ControlsPage(Page):
    def __init__(self) -> None:
        super().__init__("Remote & input")
        self.serial = label("No active device", "muted")
        self.popout = button("Pop-out Remote", icon=QStyle.StandardPixmap.SP_TitleBarNormalButton)
        self.body.addLayout(row(self.serial, self.popout))
        self.pad = RemotePad()
        self.columns = QBoxLayout(QBoxLayout.Direction.LeftToRight)
        self.columns.setSpacing(28)
        self.columns.addWidget(self.pad, 0, Qt.AlignmentFlag.AlignTop | Qt.AlignmentFlag.AlignHCenter)
        input_panel = QWidget()
        text = QVBoxLayout(input_panel)
        text.setContentsMargins(0, 16, 0, 0)
        text.setSpacing(16)
        text.addWidget(label("Send Text to TV", "section"))
        self.text = QLineEdit()
        self.text.setPlaceholderText("English / العربية")
        self.text.setAccessibleName("Send Text to TV")
        self.send = button("Send", "primary", QStyle.StandardPixmap.SP_ArrowForward)
        text.addLayout(row(self.text, self.send))
        self.text_status = label("No text sent yet.", "muted")
        text.addWidget(self.text_status)
        text.addSpacing(20)
        text.addWidget(label("Audio", "section"))
        self.audio_status = label("Audio uses the emulator's default backend.", "muted")
        text.addWidget(self.audio_status)
        text.addWidget(label("Test Sound sets the TV media volume to 10. Audible playback depends on the active TV app.", "muted"))
        text.addStretch()
        self.columns.addWidget(input_panel, 1)
        self.body.addLayout(self.columns)
        self.body.addStretch()

    def resizeEvent(self, event) -> None:
        self.columns.setDirection(QBoxLayout.Direction.LeftToRight if self.width() >= 780 else QBoxLayout.Direction.TopToBottom)
        super().resizeEvent(event)


class TVPage(Page):
    def __init__(self) -> None:
        super().__init__("TV Mode")
        self.status = label("TV Mode is off.", "status")
        self.enter = button("Enter TV Mode", "primary", QStyle.StandardPixmap.SP_TitleBarMaxButton)
        self.exit = button("Exit TV Mode", icon=QStyle.StandardPixmap.SP_TitleBarNormalButton)
        self.enter.setToolTip("Enter TV Mode (F11)")
        self.exit.setToolTip("Exit TV Mode (F11)")
        self.body.addWidget(self.status)
        self.body.addLayout(row(self.enter, self.exit))
        self.body.addWidget(label("The emulator toolbar may remain visible. Window and viewport measurements are available in Diagnostics.", "muted"))
        self.details = QPlainTextEdit()
        self.details.setReadOnly(True)
        self.body.addWidget(self.details, 1)


class PerformancePage(Page):
    def __init__(self) -> None:
        super().__init__("Performance & network")
        self.summary = label("No profile loaded.", "muted")
        self.body.addWidget(self.summary)
        form = QFormLayout()
        form.setSpacing(16)
        self.ram = QSpinBox()
        self.ram.setRange(1024, 8192)
        self.ram.setSingleStep(512)
        self.ram.setValue(2048)
        self.ram.setSuffix(" MB")
        self.cpus = QSpinBox()
        self.cpus.setRange(1, 8)
        self.cpus.setValue(2)
        self.gpu = QCheckBox("Use host GPU")
        self.gpu.setChecked(True)
        form.addRow("Memory", self.ram)
        form.addRow("CPU cores", self.cpus)
        form.addRow("Graphics", self.gpu)
        self.body.addLayout(form)
        self.apply = button("Optimize Emulator Performance", "primary", QStyle.StandardPixmap.SP_DialogApplyButton)
        self.body.addWidget(self.apply)
        self.status = label("Stop Google TV before changing performance settings.", "muted")
        self.body.addWidget(self.status)
        network = self.section("Network")
        self.network = button("Check Network", icon=QStyle.StandardPixmap.SP_BrowserReload)
        self.output = QPlainTextEdit()
        self.output.setReadOnly(True)
        self.output.setMinimumHeight(200)
        network.addWidget(self.network)
        network.addWidget(self.output)
        self.body.addStretch()
